name: Trace
description: Cryptocurrency portfolio and market explorer.

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^0.5.6
  path_provider: ^1.5.1
  flutter_circular_chart: ^0.1.0
  url_launcher: ^5.4.1
  http: any
  package_info: ^0.4.0+13

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.7.4

flutter_icons:
  android: false
  ios: true
  image_path: "assets/icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/